# This GHA workflow builds a container image and pushes it to GitHub Container Registry.
name: Build and push container image to GHCR

on:
  release:
    types: [ published ]

# Note: Individual jobs can override this default permission specification as needed.
permissions: {}

jobs:
  check-source-code-format:
    name: Check source code format
    uses: ./.github/workflows/check-source-code-format.yml
    permissions: { contents: read }
  run-tests:
    name: Run tests
    uses: ./.github/workflows/run-tests.yml
    permissions: { contents: read }
  build:
    name: Build image
    # This job depends upon other jobs succeeding.
    # Reference: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds
    needs:
      - check-source-code-format
      - run-tests
    permissions: { contents: read, packages: write }
    runs-on: ubuntu-latest
    steps:
      - name: Check out commit  # Docs: https://github.com/actions/checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # Generate tags for the Docker container images.
      - name: Generate image tags
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: |
            ghcr.io/microbiomedata/refscan
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{version}}
            type=sha

      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: |
            VERSION=${{ github.event.release.tag_name }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
